/* eslint-disable */
export const levelData = [
  {
    level: 1,
    startMoney: 1000,
    timeUnit: 800,
    GraphData: {
      startPrice: 300,
      maximumChange: 50,
      graphLength: 65,
      frameDifficultyRange: [20, 30],
      frameStartDirection: 1,
      numberOfFramePoints: 6,
      noiseLength: 1,
      noiseStrength: 0.25,
      noiseScoreRange: [1.0, 1.5],
      slumpRatio: 0.6,
    },
    itemName: '감자',
    itemImg: 'gamza.png',
    goalDesc: "감자를 팔아서, 1,300원을 만드세요!",
    goal: 1300,
  }, {
    level: 2,
    startMoney: 1000,
    timeUnit: 650,
    GraphData: {
      startPrice: 500,
      maximumChange: 80,
      graphLength: 80,
      frameDifficultyRange: [15, 20],
      frameStartDirection: 1,
      numberOfFramePoints: 8,
      noiseLength: 1,
      noiseStrength: 0.25,
      noiseScoreRange: [1.1, 1.7],
      slumpRatio: 0.8,
    },
    itemName: '토마토',
    itemImg: 'tomato.png',
    goalDesc: "토마토를 팔아서, 1,400원을 만드세요!",
    goal: 1400,
  }, {
    level: 3,
    startMoney: 1000,
    timeUnit: 500,
    GraphData: {
      startPrice: 600,
      maximumChange: 100,
      graphLength: 105,
      frameDifficultyRange: [15, 25],
      frameStartDirection: 1,
      numberOfFramePoints: 9,
      noiseLength: 1,
      noiseStrength: 0.25,
      noiseScoreRange: [1.0, 1.5],
      slumpRatio: 0.7,
    },
    itemName: '브로콜리',
    itemImg: 'brocoli.png',
    goalDesc: "브로콜리를 팔아서, 1,500원을 만드세요!",
    goal: 1500,
  },
];
